version: '3.3'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=min
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=login
    ports:
      - 3306:3306
    expose:
      - 3306
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/home
    expose:
      - 5000
    links:
      - mysql
    depends_on:
      - mysql
