version: '3'
services:
  mysql:
    container_name: flask_mysql
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=login
  app:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - '5000:5000'
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_DATABASE=login
volumes:
  mysql-data:
    driver: local
